#!/usr/bin/bash

# Ensure the repos directory exists
mkdir -p ~/repos

# symlink the files from repo to the local machine
ln -s ${PWD}/dotfiles/tmux.conf ~/.tmux.conf
ln -s ${PWD}/dotfiles/gitconfig ~/.gitconfig

git clone git@github.com:coopergillan/vim_dotfiles.git ~/.vim

cd ~/.vim
./activate.sh
